

INSERT INTO TB_TIPO_ASISTENCIAS (nombre, color_hex) VALUES

('PUNTUAL', '#008000'),
('TARDE', '#FFA500'),
('FALTA', '#FF0000'),
('J-MEDICA', '#0000FF'),
('J-OTROS', '#FF1493'),
('VACACIONES', '#808080'),
('SIN_REGISTRO', '#808080');



INSERT INTO TB_EMPLEADOS (nombre, apellido) VALUES
('ANDRES ELEUTERIO', 'LLANTO VALLEJO'),
('JADE BEATRIZ', 'VALDEZ ATENCIA'),
('ESTHER CRISTINA', 'HUAMANI BARCO'),
('JUANA', 'QUISPE CCAMA'),
('DAYRA LUCIA', 'ESTRADA FERNANDEZ'),
('DIANA ARACELLI', 'TEZEN DAVILA'),
('JOSSELIN FIORELLA', 'ROMERO EMETERIO'),
('WENDY MELANIA', 'AUCCA SANCHEZ'),
('ANGELICA MARIA', 'TAMBO CAMPOS'),
('CARMEN ISABEL', 'GONZALES MERA'),
('RUTH EVELYN', 'CCAPA HUAMANI'),
('MARIA SUSANA', 'CAJAVILCA PALACIOS'),
('RUTI ROSAURA', 'CONDORI ALLCA'),
('MARIA MILAGROS', 'FLORES PRADO'),
('OLINDA STEPHANY', 'CAHUA VARGAS'),
('LILIANA ESTHER', 'CAJAVILCA PALACIOS'),
('JUAN ROLANDO', 'CHUMBE NAVARRO'),
('DAISY KAREN', 'SEMINARIO ROSALES'),
('JULIA ELIZABETH', 'PAREDES BURGOS'),
('ROSSMERY', 'CARBAJAL HUAMANI'),
('ALMENDRA ALICIA', 'ADVINCOLA TORIBIO'),
('LILI ELIANA', 'AYALA CHAVEZ'),
('FLOR', 'MODRAGON PEREZ'),
('CYNTHIA ARACELY', 'CHUQUITUCTO LLICAN'),
('NORA MILAGROS', 'AGUILAR REYES'),
('SOFIA ESTEFANI', 'UPARI OLIVEIRA');

